menu:
  主页: /blog/
  归档: /blog/archives

logo: '林水溶'

more:
  Github: https://github.com/shuirong/
  知乎: https://www.zhihu.com/people/linShuiRong
  SegmentFault: https://segmentfault.com/u/shuirong1997
  网易云音乐: https://music.163.com/#/user/home?id=117775940
  友链: /links.html
  RSS: atom.xml
  关于我: /about.html

feed:
    type: atom
    path: atom.xml
    limit: false
    hub:
    content: false
    content_limit: 400
    content_limit_delim: ' '

about:
  title: Hexo Theme Pln
  link: https://github.com/gaoryrt/hexo-theme-pln

disqus_shortname:

excerpt_num: 120
