menu:
  主页: /
  归档: /archives

logo: 'shuiRong'

more:
  Github: https://github.com/shuirong/
  知乎: https://www.zhihu.com/people/linShuiRong
  网易云音乐: https://music.163.com/#/user/home?id=117775940
  所见: https://isee.linshuirong.cn/
  友链: /links.html
  关于我: /about.html

about:
  title: Hexo Theme Pln
  link: https://github.com/gaoryrt/hexo-theme-pln

disqus_shortname:

excerpt_num: 120
